import express from 'express';
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createDecompositionRouter } from './router.js';
import { DecompositionRepository } from './repository.js';
import { ArtifactStore } from './artifactStore.js';
import { readDecompositionConfig } from './config.js';
import { hashOperatorPassword, sessionTokenHash } from './auth.js';
import { mockPng } from '../testSupport.js';
const resources:{server:Server;repo:DecompositionRepository;dir:string}[]=[];
const origin='http://localhost:5173';const mutation={Origin:origin,'X-FrameFlow-CSRF':'1'};
async function start(){const dir=await mkdtemp(resolve(tmpdir(),'frameflow-http-'));const repo=new DecompositionRepository(dir);const store=new ArtifactStore(dir,repo);const config=readDecompositionConfig({DECOMPOSITION_ENABLED:'true',DECOMP_DATA_DIR:dir,FAL_KEY:'offline-test-only',DECOMP_OPERATOR_PASSWORD_HASH:await hashOperatorPassword('a-private-test-password')});const app=express();app.use('/api/decomposition',createDecompositionRouter(config,repo,store));const server=createServer(app);await new Promise<void>((done,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',done);});resources.push({server,repo,dir});const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/decomposition`;return{repo,store,base};}
async function login(base:string){const response=await fetch(`${base}/session`,{method:'POST',headers:{...mutation,'Content-Type':'application/json'},body:JSON.stringify({password:'a-private-test-password'})});expect(response.status).toBe(200);return response.headers.get('set-cookie')!.split(';')[0];}
afterEach(async()=>{for(const r of resources.splice(0)){r.server.closeAllConnections();await new Promise<void>((done)=>r.server.close(()=>done()));r.repo.close();await rm(r.dir,{recursive:true,force:true});}});
describe('authenticated decomposition API (no inference)',()=>{
  it('requires owner session, configured origin and CSRF and stores only hashed tokens',async()=>{const f=await start();expect((await fetch(`${f.base}/jobs`)).status).toBe(401);const body=JSON.stringify({password:'a-private-test-password'});expect((await fetch(`${f.base}/session`,{method:'POST',headers:{'Content-Type':'application/json'},body})).status).toBe(403);expect((await fetch(`${f.base}/session`,{method:'POST',headers:{...mutation,Origin:'https://evil.example','Content-Type':'application/json'},body})).status).toBe(403);const cookie=await login(f.base);const token=cookie.split('=')[1];expect(f.repo.sessionOwner(sessionTokenHash(token))).toBe('operator');expect(f.repo.db.prepare('SELECT token_hash FROM sessions').get()).toEqual({token_hash:sessionTokenHash(token)});expect((await fetch(`${f.base}/jobs`,{headers:{Cookie:cookie}})).status).toBe(200);});
  it('validates streamed image before persisting source and rejects arbitrary URLs',async()=>{const f=await start();const cookie=await login(f.base);const malformed=new FormData();malformed.set('image',new Blob(['not a png'],{type:'image/png'}),'source.png');expect((await fetch(`${f.base}/assets`,{method:'POST',headers:{...mutation,Cookie:cookie},body:malformed})).status).toBe(422);expect(f.repo.db.prepare('SELECT COUNT(*) n FROM source_assets').get()).toEqual({n:0});const form=new FormData();form.set('image',new Blob([new Uint8Array(mockPng(257,259))],{type:'image/png'}),'source.png');const upload=await fetch(`${f.base}/assets`,{method:'POST',headers:{...mutation,Cookie:cookie},body:form});expect(upload.status).toBe(201);const source=await upload.json() as {id:string;width:number;height:number;previewArtifactId:string};expect(source).toMatchObject({width:257,height:259});const artifact=await fetch(`${f.base}/artifacts/${source.previewArtifactId}`,{headers:{Cookie:cookie}});expect(artifact.status).toBe(200);expect(artifact.headers.get('x-content-type-options')).toBe('nosniff');expect((await fetch(`${f.base}/artifacts/${source.previewArtifactId}`)).status).toBe(401);const create=await fetch(`${f.base}/jobs`,{method:'POST',headers:{...mutation,Cookie:cookie,'Content-Type':'application/json','Idempotency-Key':'valid-key-123'},body:JSON.stringify({sourceId:source.id,options:{}})});expect(create.status).toBe(202);const job=await create.json() as {id:string;sourceWidth:number};expect(job.sourceWidth).toBe(257);expect((await fetch(`${f.base}/jobs`,{method:'POST',headers:{...mutation,Cookie:cookie,'Content-Type':'application/json','Idempotency-Key':'valid-key-456'},body:JSON.stringify({sourceUrl:'http://169.254.169.254/latest',options:{}})})).status).toBe(400);});
});
