import { mkdir, open, rename, readFile, cp } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { readDecompositionConfig } from './config.js';
import { hashOperatorPassword } from './auth.js';
import { DecompositionRepository } from './repository.js';
async function hiddenPassword():Promise<string>{
  if(!process.stdin.isTTY)throw new Error('Run setup in an interactive terminal. Password input is never read from command-line arguments.');
  process.stdout.write('Operator password (at least 12 characters): ');const input=process.stdin;input.setRawMode(true);input.resume();let value='';
  return new Promise((resolvePassword,reject)=>{const onData=(chunk:Buffer)=>{for(const char of chunk.toString('utf8')){if(char==='\r'||char==='\n'){input.off('data',onData);input.setRawMode(false);input.pause();process.stdout.write('\n');resolvePassword(value);return;}if(char==='\u0003'){input.off('data',onData);input.setRawMode(false);input.pause();reject(new Error('Setup cancelled.'));return;}if(char==='\u007f')value=value.slice(0,-1);else if(value.length<1024)value+=char;}};input.on('data',onData);});
}
export async function backupDecomposition(dataDir:string,destination:string){await mkdir(destination,{recursive:true,mode:0o700});const repo=new DecompositionRepository(dataDir);try{await repo.backup(resolve(destination,'decomposition.sqlite'));await cp(resolve(dataDir,'artifacts'),resolve(destination,'artifacts'),{recursive:true,errorOnExist:true,force:false});await cp(resolve(dataDir,'operator.json'),resolve(destination,'operator.json'),{errorOnExist:true,force:false}).catch((error:NodeJS.ErrnoException)=>{if(error.code!=='ENOENT')throw error;});}finally{repo.close();}}
export async function restoreDecomposition(backupDir:string,destination:string){await mkdir(destination,{recursive:true,mode:0o700});const entries=await import('node:fs/promises').then((fs)=>fs.readdir(destination));if(entries.length)throw new Error('Restore destination must be empty.');await readFile(resolve(backupDir,'decomposition.sqlite'));for(const entry of await import('node:fs/promises').then((fs)=>fs.readdir(backupDir)))await cp(resolve(backupDir,entry),resolve(destination,entry),{recursive:true,force:false,errorOnExist:true});const repo=new DecompositionRepository(destination);const check=repo.db.pragma('integrity_check',{simple:true});repo.close();if(check!=='ok')throw new Error('Restored SQLite integrity check failed.');}
async function main(){const command=process.argv[2];const config=readDecompositionConfig({...process.env,DECOMPOSITION_ENABLED:'false'});if(command==='backup'){if(!process.argv[3])throw new Error('Provide a backup directory. Stop the worker and API while backing up artifacts.');await backupDecomposition(config.dataDir,resolve(process.argv[3]));process.stdout.write('Backup complete.\n');return;}if(command==='restore'){if(!process.argv[3]||!process.argv[4])throw new Error('Provide backup directory and empty restore directory.');await restoreDecomposition(resolve(process.argv[3]),resolve(process.argv[4]));process.stdout.write('Restore integrity check passed.\n');return;}
  await mkdir(config.dataDir,{recursive:true,mode:0o700});const repo=new DecompositionRepository(config.dataDir);repo.close();const password=await hiddenPassword();const passwordHash=await hashOperatorPassword(password);const file=resolve(config.dataDir,'operator.json');const temp=`${file}.${randomUUID()}.tmp`;const handle=await open(temp,'wx',0o600);await handle.writeFile(JSON.stringify({passwordHash}));await handle.sync();await handle.close();await rename(temp,file);process.stdout.write('Operator credentials saved privately. Set DECOMPOSITION_ENABLED=true and FAL_KEY in the server environment, then start API and worker.\n');
}
// Keep imports usable for deterministic backup/restore tests.
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch((error:unknown)=>{process.stderr.write(`${error instanceof Error?error.message:'Setup failed'}\n`);process.exitCode=1;});
