/** Separate collection: the five original curated definitions stay unchanged. */
import type { OfferTemplateDefinition } from './offerTemplates.js';
import type { PremiumLayout, ThemeSpec } from './themeSpec.js';
const spec = (templateName: string, archetype: PremiumLayout, style: ThemeSpec['style'], palette: ThemeSpec['palette'], headline: string, body: string, content: Partial<ThemeSpec['content']>): ThemeSpec => ({
  templateName, style, palette, typography: { headline, offer: 'Montserrat', body, cta: body },
  content: { eyebrow: 'THE FESTIVAL OF LIGHT', headline: 'Celebrate Diwali', subheadline: 'A season of light. A world of possibility.', offerPrefix: '', offerValue: '', offerSuffix: '', cta: 'DISCOVER MORE  →', terms: '*T&C apply', date: '', location: '', ...content },
  layout: { archetype, heroPlacement: 'center', textAlignment: 'center' }, background: 'DARK_PREMIUM', decorations: ['LANTERN','BOKEH'], slots: { logo: true, product: ['PREMIUM_ECOMMERCE_SALE','PREMIUM_PRODUCT_GIFT'].includes(archetype), heroImage: ['PREMIUM_JEWELLERY_OFFER','ELEGANT_GREETING','LANTERN_NIGHT'].includes(archetype) },
});
export const PREMIUM_DIWALI_TEMPLATES: readonly OfferTemplateDefinition[] = [
  { id:'premium-jewellery', name:'Premium Jewellery Festive Offer', festival:'diwali', category:'Jewellery · Dual offer', description:'Burnished orange, two bold offers and a celebration in focus.', spec:spec('Premium Jewellery Festive Offer','PREMIUM_JEWELLERY_OFFER','sale',{background:'#521305',primary:'#CB560B',accent:'#FFDF94',text:'#FFF4DC'},'Montserrat','Poppins',{eyebrow:'THE FESTIVE JEWELLERY EDIT',headline:'Shine a little brighter.',subheadline:'A celebration of you.',offerValue:'50%',offerPrefix:'SAVE UP TO',offerSuffix:'ON GOLD MAKING CHARGES',secondOfferValue:'30%',secondOfferLabel:'ON DIAMOND JEWELLERY',cta:'EXPLORE THE COLLECTION  →',date:'A NEW SEASON OF CELEBRATION',location:'YOUR SHOWROOM · YOUR CITY'}) },
  { id:'premium-ecommerce', name:'Premium Ecommerce Festival Sale', festival:'diwali', category:'Shopping · Festival sale', description:'Maroon, luminous gold and a generous product showcase.', spec:spec('Premium Ecommerce Festival Sale','PREMIUM_ECOMMERCE_SALE','sale',{background:'#260812',primary:'#711D2A',accent:'#F4C66A',text:'#FFF1D5'},'Montserrat','Poppins',{eyebrow:'THE BIG FESTIVE EDIT',headline:'Great Diwali\nFestival',subheadline:'Extraordinary finds. Unforgettable gifts.',offerPrefix:'FESTIVE SAVINGS',offerValue:'UP TO 50% OFF',cta:'SHOP THE FESTIVAL  →',date:'SALE STARTS 20 OCTOBER'}) },
  { id:'premium-greeting', name:'Elegant Diwali Greeting', festival:'diwali', category:'Brand · Elegant greeting', description:'Indigo, quiet serif lettering and the warmth of a diya.', spec:spec('Elegant Diwali Greeting','ELEGANT_GREETING','greeting',{background:'#181538',primary:'#3A3275',accent:'#EACA91',text:'#FFF3DB'},'DM Serif Display','Poppins',{eyebrow:'MAY YOUR WORLD SHINE',headline:'Happy\nDiwali',subheadline:'May the light you share\ncome back to you a thousandfold.',cta:'SHARE THE LIGHT  →',terms:'With warmth, from all of us.'}) },
  { id:'premium-lantern', name:'Lantern Night Celebration', festival:'diwali', category:'Greeting · Lantern night', description:'Glowing lanterns, a night sky and a message of togetherness.', spec:spec('Lantern Night Celebration','LANTERN_NIGHT','greeting',{background:'#10132F',primary:'#282447',accent:'#FFC46D',text:'#FFF4E4'},'Cormorant Garamond','Poppins',{eyebrow:'A THOUSAND LIGHTS. ONE CELEBRATION.',headline:'Let your\nlight rise.',subheadline:'Happy Diwali\nHere’s to love, laughter and brighter tomorrows.',cta:'CELEBRATE TOGETHER  →',terms:'Light brings us together.'}) },
  { id:'premium-event', name:'Premium Diwali Event Invite', festival:'diwali', category:'Invitation · Festive evening', description:'Illuminated architecture and an invitation in plum and gold.', spec:spec('Premium Diwali Event Invite','PREMIUM_EVENT','event',{background:'#200F31',primary:'#752453',accent:'#FFD078',text:'#FFF0DF'},'Cinzel','Poppins',{eyebrow:'YOU ARE INVITED TO',headline:'Diwali\nAfter Dark',subheadline:'DIWALI TREATS · MUSIC · MEMORIES',date:'SATURDAY · 24 OCTOBER',time:'7 PM ONWARDS',dressCode:'DRESS CODE · FESTIVE ELEGANCE',location:'YOUR VENUE · YOUR CITY',cta:'RESERVE YOUR EVENING  →',terms:'An evening made for celebration.'}) },
  { id:'premium-gift', name:'Premium Product Gift Campaign', festival:'diwali', category:'Luxury · Product gifting', description:'Amber light, tactile gifting and a beautifully quiet product story.', spec:spec('Premium Product Gift Campaign','PREMIUM_PRODUCT_GIFT','product',{background:'#211209',primary:'#664127',accent:'#DAB87B',text:'#FFF0DA'},'Cormorant Garamond','Poppins',{eyebrow:'THE ART OF THOUGHTFUL GIVING',headline:'A gift of radiance.',subheadline:'Beautifully chosen. Warmly remembered.\nShare a little light this Diwali.',cta:'DISCOVER THE GIFT EDIT  →',terms:'Thoughtful gifts. Lasting impressions.'}) },
];
