import { expect, test } from '@playwright/test';

test('Create Template from Image stores 13 raw candidates but previews, imports and reopens only 6 curated layers', async ({ page, request }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'One full route journey; viewport regressions are covered separately.');
  test.setTimeout(120_000);
  page.on('dialog', dialog => void dialog.accept());
  await page.route(url => /^https?:$/.test(url.protocol) && url.hostname !== '127.0.0.1', route => route.abort());
  await page.goto('/');
  await page.getByRole('button', { name: 'OpenAI + Seedream test' }).click();
  await page.getByRole('tab', { name: 'Create Template', exact: true }).click();
  await page.getByRole('button', { name: 'Create Template from Image', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Create Template from Image' });
  await dialog.getByRole('button', { name: 'New template' }).click();
  await dialog.getByLabel('Legacy prompt workflow').check();
  const name = `Curated mint phone ${Date.now()}`;
  await dialog.getByLabel('Template name').fill(name);
  await dialog.getByLabel('Reference image', { exact: true }).setInputFiles({ name: 'mint-phone.png', mimeType: 'image/png', buffer: await (await request.get('/__test__/reference.png')).body() });
  await dialog.getByRole('checkbox', { name: '16:9 Landscape' }).uncheck();
  await dialog.getByRole('checkbox', { name: '4:5 Portrait' }).uncheck();
  await dialog.getByRole('button', { name: 'Generate prompt from image' }).click();
  await expect(dialog.getByLabel('Generated prompt')).toHaveValue(/lavender/, { timeout: 10_000 });
  await dialog.getByLabel('Generated prompt').fill('Mint phone curation fixture: seated person holding a phone, side product, headline, Pro badge and secondary text.');
  await dialog.getByRole('button', { name: 'Generate selected templates (1)' }).click();
  const card = dialog.getByRole('article', { name: '1:1 result' });
  await expect(card.getByTestId('status-1x1')).toHaveText('Generated', { timeout: 15_000 });
  await card.getByRole('button', { name: 'Decompose into layers' }).click();
  await expect(card.getByTestId('status-1x1')).toHaveText('Decomposed', { timeout: 60_000 });
  await card.getByText('Preview layers', { exact: true }).click();
  await expect(card.locator('.cti-layer-previews img')).toHaveCount(6);
  const headers = { Origin: new URL(page.url()).origin };
  const templates = (await (await request.get('/api/layerize-experiment/image-templates', { headers })).json()).templates;
  const template = templates.find((t: { name: string }) => t.name === name), runId = template.variants[0].decomposition.runId;
  const run = await (await request.get(`/api/layerize-experiment/runs/${runId}`, { headers })).json();
  expect(run.refinement.curation.counts).toMatchObject({ rawLayers: 13, editorLayers: 6 });
  expect(run.calls).toMatchObject({ seedreamResidual: 0, backgroundReconstruction: 0 });
  expect(run.editorLayerFiles).toEqual(run.outputLayers.map((l: { file: string }) => l.file));
  expect(run.outputLayers.filter((l: { placement: { kind: string } }) => l.placement.kind === 'base')).toHaveLength(1);
  for (const fragment of ['Seated model', 'Oversized phone product', 'Headline', 'Pro badge', 'Chinese secondary text'])
    expect(run.outputLayers.some((l: { name: string }) => l.name.includes(fragment)), fragment).toBe(true);
  for (const name of ['Layer 0', 'Scene plate', 'Translucent oversized-phone shadow', 'Headline outline', 'Fallback helper', 'Layer 12', 'Duplicate phone product'])
    expect(run.outputLayers.some((l: { name: string }) => l.name === name), name).toBe(false);
  const debug = await (await request.get(`/api/layerize-experiment/runs/${runId}/files/decomposition-debug.json`, { headers })).json();
  expect(debug.rawLayers).toHaveLength(13);
  const technical = debug.curation.entries.filter((e: { editorVisible: boolean }) => !e.editorVisible).map((e: { file: string }) => `/files/${e.file}`);
  const fetched: string[] = [];
  page.on('request', r => fetched.push(new URL(r.url()).pathname));
  await card.getByRole('button', { name: 'Open in editor', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const layers = page.getByRole('list', { name: 'Design layers' });
  await expect(layers.locator('li')).toHaveCount(6);
  await expect(layers).not.toContainText(/Layer 0|Fallback helper|Layer 12|Duplicate phone/);
  expect(fetched.filter(url => technical.some((path: string) => url.endsWith(path)))).toEqual([]);
  await expect(page.getByLabel('Open design').locator('option:checked')).toHaveText(`${name} · 1:1 · 1 version`);
  await page.screenshot({ path: testInfo.outputPath('curated-editor.png') });
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible();
  await page.reload();
  await expect(layers.locator('li')).toHaveCount(6);
  await expect(page.getByLabel('Active version')).toHaveCount(0);
  // The diagnostic dashboard reads these persisted facts; opening/reopening never calls a provider.
  const callsBefore = await (await request.get('/__test__/call-counts')).json();
  await page.getByRole('button', { name: 'OpenAI + Seedream test' }).click();
  const panel = page.getByRole('dialog', { name: 'OpenAI + Seedream test' });
  await panel.getByRole('tab', { name: 'Saved Runs' }).click();
  await panel.getByRole('textbox', { name: 'Search saved runs' }).fill(runId);
  await panel.getByLabel('Filter runs by status').selectOption('READY FOR EDITOR');
  await expect(panel.getByRole('article')).toHaveCount(1);
  await panel.getByRole('textbox', { name: 'Search saved runs' }).fill('no-such-run');
  await expect(panel.getByRole('heading', { name: 'No matching runs' })).toBeVisible();
  await panel.getByRole('button', { name: 'Clear filters' }).click();
  await page.screenshot({ path: testInfo.outputPath('saved-runs-desktop.png') });
  await panel.getByRole('article', { name: `Saved run ${runId}`, exact: true }).getByRole('button', { name: 'View run' }).click();
  await expect(panel.getByRole('status')).toHaveText('READY FOR EDITOR');
  await expect(panel.getByTestId('run-cost')).toHaveText('Calculated ₹56.01');
  await expect(panel.getByTestId('cost-reference')).toContainText('₹0.41');
  await expect(panel.getByTestId('cost-generation')).toContainText('₹5.90');
  await expect(panel.getByTestId('cost-planner')).toContainText('₹10.22');
  await expect(panel.getByTestId('cost-seedream')).toContainText('₹39.49');
  await expect(panel.getByTestId('cost-residual')).toContainText('₹0.00');
  await expect(panel.getByTestId('cost-background')).toContainText('₹0.00');
  await expect(panel.getByTestId('layer-story')).toHaveText('13 → 6');
  await expect(panel.getByTestId('cost-target')).toContainText('Above ₹33 target by ₹23.01');
  await expect(panel.getByRole('region', { name: 'Pipeline', exact: true })).toContainText('Generate image');
  await expect(panel.getByTestId('editor-layer-grid').locator('img')).toHaveCount(6);
  await expect(panel.getByTestId('raw-layer-grid')).toHaveCount(0);
  await expect(panel.getByText('offline-planner-request', { exact: false })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath('dashboard-desktop.png') });
  await panel.getByTestId('editor-layer-grid').scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('editor-layer-grid.png') });
  await panel.getByText('Raw / internal layers (13)', { exact: true }).click();
  await expect(panel.getByTestId('raw-layer-grid').locator('img')).toHaveCount(13);
  await expect(panel.getByTestId('raw-layer-grid')).toContainText('Translucent oversized-phone shadow');
  await panel.getByText('Raw / internal layers (13)', { exact: true }).click();
  await panel.getByText('Planner instructions', { exact: true }).click();
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await panel.getByRole('button', { name: 'Copy', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Copied', exact: true })).toBeVisible();
  await panel.getByText('Planner instructions', { exact: true }).click();
  await panel.getByText('Developer details', { exact: true }).click();
  await expect(panel.getByText('offline-planner-request', { exact: false })).toBeVisible();
  await panel.getByText('Developer details', { exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await panel.locator('.ws-body').evaluate(el => { el.scrollTop = 0; });
  await expect(panel.getByTestId('run-cost')).toBeVisible();
  expect(await panel.locator('.ws-body').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('dashboard-narrow.png') });
  await panel.getByTestId('cost-seedream').scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('dashboard-narrow-costs.png') });
  await panel.getByRole('tab', { name: 'Saved Runs' }).click();
  expect(await panel.locator('.ws-body').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await expect(panel.getByRole('article', { name: `Saved run ${runId}`, exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('saved-runs-narrow.png') });
  await page.reload();
  await page.getByRole('button', { name: 'OpenAI + Seedream test' }).click();
  await panel.getByRole('tab', { name: 'Saved Runs' }).click();
  await panel.getByRole('article', { name: `Saved run ${runId}`, exact: true }).getByRole('button', { name: 'View run' }).click();
  await expect(panel.getByTestId('run-cost')).toHaveText('Calculated ₹56.01');
  await expect(panel.getByTestId('layer-story')).toHaveText('13 → 6');
  expect(await (await request.get('/__test__/call-counts')).json()).toEqual(callsBefore);
  // A persisted failure shows the known subtotal plus an unknown potential charge.
  const failure = await (await request.post(`/__test__/dashboard-failure/${runId}`)).json();
  await page.reload();
  await page.getByRole('button', { name: 'OpenAI + Seedream test' }).click();
  await panel.getByRole('tab', { name: 'Saved Runs' }).click();
  await panel.getByRole('article', { name: `Saved run ${failure.id}`, exact: true }).getByRole('button', { name: 'View run' }).click();
  await expect(panel.getByRole('status')).toHaveText('FAILED');
  await expect(panel.getByTestId('run-cost')).toHaveText('₹16.53 known + unknown');
  await expect(panel.getByTestId('cost-seedream')).toContainText('Unknown');
  await expect(panel.getByRole('alert')).toContainText('could not produce a valid decomposition');
  await expect(panel.getByTestId('editor-layer-grid').locator('img')).toHaveCount(0);
  await page.setViewportSize({ width: 1440, height: 900 });
  await panel.locator('.ws-body').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: testInfo.outputPath('dashboard-failure.png') });
  expect(await (await request.get('/__test__/call-counts')).json()).toEqual(callsBefore);

});
